server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: user
      password: '{noop}1234'

logging:
  level:
    org:
      springframework:
        security: DEBUG